#!env python
import os
import datetime

user = os.getenv("GITHUB_ACTOR")
user_name = os.getenv("USER_NAME")
if user_name is None or user_name == "null":
    user_name = user

template = """
<html>
    <head>
        <title>Page generated by {name} at {now}</title>
    </head>
    <body><h1>Hello from {name}!</h1></body>
</html>
"""
html = template.format(
    name=user_name,
    now=datetime.datetime.now().isoformat()
)
print(html)
