# This is a basic workflow to help you get started with Actions

name: Demo

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch user name gratuitously
        run: echo "USER_NAME=$(curl ${{github.event.sender.url}} | jq -r .name)" >> $GITHUB_ENV
      - name: Configure git
        run: |
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git config --global user.name "$USER_NAME"
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Make HTML on the console
        run: python make_html.py > build_index.html
      - name: Switch branches
        run: git checkout publish
      - name: Update index
        run: mv build_index.html index.html
      - name: Commit and push
        run: git add index.html && git commit -am'Updated index page in Demo action.' && git push
